default_job = "clippy"

[jobs.clippy]
command = [
  "cargo",
  "clippy",
  "--color",
  "always",
  "--no-deps",
  "--",
  "-W",
  "clippy::pedantic",
  "-W",
  "clippy::nursery",
  "-W",
  "clippy::perf",
  "-W",
  "clippy::unwrap_used",
  "-W",
  "clippy::expect_used",
]
need_stdout = true

[jobs.clippy-ue]
command = [
  "cargo",
  "clippy",
  "--color",
  "always",
  "--no-deps",
  "--",
  "-W",
  "clippy::pedantic",
  "-W",
  "clippy::nursery",
  "-W",
  "clippy::perf",
]
need_stdout = true


[jobs.test]
command = ["cargo", "nextest", "run", "--color", "always"]
need_stdout = true

[jobs.doc]
command = ["cargo", "doc", "--color", "always", "--no-deps"]
need_stdout = false

# If the doc compiles, then it opens in your browser and bacon switches
# to the previous job
[jobs.doc-open]
command = ["cargo", "doc", "--color", "always", "--no-deps", "--open"]
need_stdout = false
on_success = "back"                                                    # so that we don't open the browser at each change

[jobs.run]
command = ["cargo", "run", "--color", "always"]
need_stdout = true
allow_warnings = true
background = false

[keybindings]
c = "job:clippy"
e = "job:clippy-ue"
