[[job]]
name = "chem"
port = 8000
dir = "~/Notes"

[[job]]
name = "math"
port = 8001
dir = "~/Notes"

[[job]]
name = "french"
port = 8002
dir = "~/Notes"

[[job]]
name = "csp"
port = 8003
dir = "~/Notes"
